import { IChallengeRepository } from "../../../../domain/repositories/challenge/IChallengeRepository";
import {
  Challenge,
  ChallengeDifficulty,
  ChallengeDomain,
} from "../../../../domain/entities/challenge/Challenge";
import { CreateChallengeDTO } from "../../../dto/challenge/CreateChallengeDTO";



export class CreateChallengeUseCase {
  constructor(
    private readonly challengeRepo: IChallengeRepository
  ) {}

  async execute(input: CreateChallengeDTO): Promise<Challenge> {
    if (!input.title?.trim()) {
      throw new Error("TITLE_REQUIRED");
    }

    if (!input.description?.trim()) {
      throw new Error("DESCRIPTION_REQUIRED");
    }

    if (!input.difficulty) {
      throw new Error("DIFFICULTY_REQUIRED");
    }

    if (!input.domain) {
      throw new Error("DOMAIN_REQUIRED");
    }

    if (typeof input.xpReward !== "number" || input.xpReward <= 0) {
      throw new Error("XP_REWARD_INVALID");
    }

    if (
      input.timeLimitMinutes !== undefined &&
      input.timeLimitMinutes <= 0
    ) {
      throw new Error("TIME_LIMIT_INVALID");
    }

    // Create DOMAIN ENTITY
    const challenge = new Challenge(
      undefined, // id (generated by DB)
      input.title.trim(),
      input.description.trim(),
      input.difficulty as ChallengeDifficulty,
      input.domain as ChallengeDomain,
      input.xpReward,
      input.timeLimitMinutes,
      input.isPremium ?? false,
      false,        // isActive
      "draft",      // status
      null,
      null
    );

    return this.challengeRepo.create(challenge);
  }
}








// import { IChallengeRepository } from "../../../../domain/repositories/challenge/IChallengeRepository";
// import {
//   IChallenge,
//   ChallengeDifficulty,
//   ChallengeDomain,
// } from "../../../../domain/entities/challenge/Challenge";
// import { CreateChallengeDTO } from "../../../dto/challenge/CreateChallengeDTO";

// export class CreateChallengeUseCase {
//   constructor(
//     private readonly challengeRepo: IChallengeRepository
//   ) {}

//   async execute(input: CreateChallengeDTO): Promise<IChallenge> {
//     if (!input.title || !input.title.trim()) {
//       throw new Error("TITLE_REQUIRED");
//     }

//     if (!input.description || !input.description.trim()) {
//       throw new Error("DESCRIPTION_REQUIRED");
//     }

//     if (!input.difficulty) {
//       throw new Error("DIFFICULTY_REQUIRED");
//     }

//     if (!input.domain) {
//       throw new Error("DOMAIN_REQUIRED");
//     }

//     if (typeof input.xpReward !== "number" || input.xpReward <= 0) {
//       throw new Error("XP_REWARD_INVALID");
//     }

//     if (
//       input.timeLimitMinutes !== undefined &&
//       input.timeLimitMinutes <= 0
//     ) {
//       throw new Error("TIME_LIMIT_INVALID");
//     }

//     const challenge: IChallenge = {
//       title: input.title.trim(),
//       description: input.description.trim(),
//       difficulty: input.difficulty as ChallengeDifficulty,
//       domain: input.domain as ChallengeDomain,
//       xpReward: input.xpReward,
//       timeLimitMinutes: input.timeLimitMinutes,
//       isPremium: input.isPremium ?? false,
//       isActive: false,
//       status: "draft",
//     };

//     return this.challengeRepo.create(challenge);
//   }
// }
