name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download Frontend Dist       # ADD THIS
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend-dist
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}


      - name: Fix permissions on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo chown -R ubuntu:ubuntu /var/www/html     
            

      - name: Copy dist to EC2             # ADD THIS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "frontend-dist/*"
          target: "/var/www/html/"
          strip_components: 1

      - name: Deploy Backend to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 10m
          script: |
            set -e
            echo "🚀 Starting Deployment..."
            cd /home/ubuntu/code-clash
            git fetch origin
            git reset --hard origin/main

            # ===== BACKEND =====
            echo "🐳 Checking backend changes..."
            if git diff --name-only HEAD~1 HEAD | grep -E "backend|docker-compose.yml"; then
              echo "Backend changed → deploying..."
              docker-compose up -d --build backend
            else
              echo "No backend changes → skipping"
            fi

            # ===== FRONTEND — just reload nginx =====
            sudo systemctl reload nginx
            echo "✅ Deployment Complete!"